# _config.yml
title: Ashfin Enayet
description: Personal Website
#theme: jekyll-theme-minimal # You can change this to the Jekyll theme of your choice

# GitHub Pages settings
remote_theme: pages-themes/cayman@v0.2.0 # If you're using a GitHub-hosted theme
baseurl: "" # Leave this blank for the root of the repository
url: "https://yourusername.github.io" # Replace with your GitHub Pages URL

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Other site-specific configuration
# Add any other configuration settings you need for your site
